/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TubesPBO_InnerPeace;

import java.awt.Color;

/**
 *
 * @author Aspire 5
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMakeAppointment = new javax.swing.JButton();
        jButtonDiary = new javax.swing.JButton();
        jUserMenuLabel2 = new javax.swing.JLabel();
        jUserMenuLabel = new javax.swing.JLabel();
        jRainbowBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InnerPeace");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        setForeground(new java.awt.Color(153, 204, 255));
        setPreferredSize(new java.awt.Dimension(709, 483));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMakeAppointment.setBackground(new java.awt.Color(51, 51, 255));
        jButtonMakeAppointment.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jButtonMakeAppointment.setForeground(new java.awt.Color(0, 102, 153));
        jButtonMakeAppointment.setText("Make Appointment");
        jButtonMakeAppointment.setActionCommand("Make Appointment");
        jButtonMakeAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMakeAppointmentActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMakeAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 390, 70));

        jButtonDiary.setBackground(new java.awt.Color(51, 51, 255));
        jButtonDiary.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jButtonDiary.setForeground(new java.awt.Color(0, 102, 153));
        jButtonDiary.setLabel("My Personal Diary");
        getContentPane().add(jButtonDiary, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 390, 70));

        jUserMenuLabel2.setBackground(new java.awt.Color(255, 204, 204));
        jUserMenuLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jUserMenuLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jUserMenuLabel2.setText("How can we help?");
        jUserMenuLabel2.setName(""); // NOI18N
        getContentPane().add(jUserMenuLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 380, 90));

        jUserMenuLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jUserMenuLabel.setForeground(new java.awt.Color(0, 102, 153));
        jUserMenuLabel.setText("Hello! *userName*");
        jUserMenuLabel.setName(""); // NOI18N
        getContentPane().add(jUserMenuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 380, 90));
        jUserMenuLabel.getAccessibleContext().setAccessibleName("jUserMenuLabel");

        jRainbowBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TubesPBO_InnerPeace/ombreBackGround.jpg"))); // NOI18N
        jRainbowBackground.setText("jLabel1");
        jRainbowBackground.setPreferredSize(new java.awt.Dimension(709, 483));
        getContentPane().add(jRainbowBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMakeAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMakeAppointmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMakeAppointmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDiary;
    private javax.swing.JButton jButtonMakeAppointment;
    private javax.swing.JLabel jRainbowBackground;
    private javax.swing.JLabel jUserMenuLabel;
    private javax.swing.JLabel jUserMenuLabel2;
    // End of variables declaration//GEN-END:variables
}
