/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OOP_InnerPeace;

import java.awt.Color;

/**
 *
 * @author Aspire 5
 */
public class MenuOnlineConsultationUser extends javax.swing.JFrame {

    /**
     * Creates new form MenuUser
     */
    public MenuOnlineConsultationUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioButtonDiaryPrivacy = new javax.swing.ButtonGroup();
        ButtonShortcutAppointment = new javax.swing.JButton();
        ButtonChatConsultant = new javax.swing.JButton();
        LabelGreetingDiary = new javax.swing.JLabel();
        LabelGreetingDiary3 = new javax.swing.JLabel();
        LabelGreetingDiary1 = new javax.swing.JLabel();
        LabelGreetingDiary2 = new javax.swing.JLabel();
        ButtonBack = new javax.swing.JButton();
        LogoInnerPeace = new javax.swing.JLabel();
        jBackground = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InnerPeace");
        setName("MenuUser"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(709, 483));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonShortcutAppointment.setBackground(java.awt.Color.pink);
        ButtonShortcutAppointment.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        ButtonShortcutAppointment.setForeground(new java.awt.Color(0, 102, 153));
        ButtonShortcutAppointment.setText("Make an Appointment");
        ButtonShortcutAppointment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonShortcutAppointment.setBorderPainted(false);
        ButtonShortcutAppointment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonShortcutAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonShortcutAppointmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonShortcutAppointmentMouseExited(evt);
            }
        });
        ButtonShortcutAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonShortcutAppointmentActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonShortcutAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 340, 60));

        ButtonChatConsultant.setBackground(java.awt.Color.pink);
        ButtonChatConsultant.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        ButtonChatConsultant.setForeground(new java.awt.Color(0, 102, 153));
        ButtonChatConsultant.setText("Talk to a Consultant");
        ButtonChatConsultant.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonChatConsultant.setBorderPainted(false);
        ButtonChatConsultant.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonChatConsultant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonChatConsultantMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonChatConsultantMouseExited(evt);
            }
        });
        ButtonChatConsultant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChatConsultantActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonChatConsultant, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 340, 60));

        LabelGreetingDiary.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        LabelGreetingDiary.setForeground(new java.awt.Color(0, 102, 153));
        LabelGreetingDiary.setText("Meet with a Consultant");
        getContentPane().add(LabelGreetingDiary, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 400, 60));

        LabelGreetingDiary3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        LabelGreetingDiary3.setForeground(new java.awt.Color(255, 255, 255));
        LabelGreetingDiary3.setText("Talk face-to-face with a consultant");
        getContentPane().add(LabelGreetingDiary3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 380, 80));

        LabelGreetingDiary1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        LabelGreetingDiary1.setForeground(new java.awt.Color(0, 102, 153));
        LabelGreetingDiary1.setText("Online Consultation");
        getContentPane().add(LabelGreetingDiary1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 400, 70));

        LabelGreetingDiary2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        LabelGreetingDiary2.setForeground(new java.awt.Color(255, 255, 255));
        LabelGreetingDiary2.setText("Don't feel like going out? Online consultation is da wae out. ;)");
        getContentPane().add(LabelGreetingDiary2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 600, 30));

        ButtonBack.setBackground(java.awt.Color.pink);
        ButtonBack.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        ButtonBack.setForeground(new java.awt.Color(0, 102, 153));
        ButtonBack.setText("Back to Main Menu");
        ButtonBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonBack.setBorderPainted(false);
        ButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonBackMouseExited(evt);
            }
        });
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 160, 40));

        LogoInnerPeace.setIcon(new javax.swing.ImageIcon("D:\\Buat kuliah\\Semester 2\\OOP\\TugasBesar\\TubesInnerPeace\\src\\main\\java\\OOP_InnerPeace\\logo_innerpeace1.png")); // NOI18N
        getContentPane().add(LogoInnerPeace, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 250, 480));

        jBackground.setBackground(new java.awt.Color(77, 150, 255));
        getContentPane().add(jBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void ButtonChatConsultantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonChatConsultantMouseEntered
        ButtonChatConsultant.setBackground(Color.lightGray);
    }//GEN-LAST:event_ButtonChatConsultantMouseEntered

    private void ButtonChatConsultantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonChatConsultantMouseExited
        ButtonChatConsultant.setBackground(Color.pink);
    }//GEN-LAST:event_ButtonChatConsultantMouseExited

    private void ButtonChatConsultantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChatConsultantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonChatConsultantActionPerformed

    private void ButtonShortcutAppointmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonShortcutAppointmentMouseEntered
        ButtonShortcutAppointment.setBackground(Color.lightGray);
    }//GEN-LAST:event_ButtonShortcutAppointmentMouseEntered

    private void ButtonShortcutAppointmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonShortcutAppointmentMouseExited
        ButtonShortcutAppointment.setBackground(Color.pink);
    }//GEN-LAST:event_ButtonShortcutAppointmentMouseExited

    private void ButtonShortcutAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonShortcutAppointmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonShortcutAppointmentActionPerformed

    private void ButtonBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBackMouseEntered
        ButtonBack.setBackground(Color.lightGray);
    }//GEN-LAST:event_ButtonBackMouseEntered

    private void ButtonBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBackMouseExited
        ButtonBack.setBackground(Color.pink);
    }//GEN-LAST:event_ButtonBackMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOnlineConsultationUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOnlineConsultationUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOnlineConsultationUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOnlineConsultationUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOnlineConsultationUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonChatConsultant;
    private javax.swing.JButton ButtonShortcutAppointment;
    private javax.swing.JLabel LabelGreetingDiary;
    private javax.swing.JLabel LabelGreetingDiary1;
    private javax.swing.JLabel LabelGreetingDiary2;
    private javax.swing.JLabel LabelGreetingDiary3;
    private javax.swing.JLabel LogoInnerPeace;
    private javax.swing.ButtonGroup RadioButtonDiaryPrivacy;
    private javax.swing.JPanel jBackground;
    // End of variables declaration//GEN-END:variables
}
