/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OOP_InnerPeace;

import java.awt.Color;

/**
 *
 * @author Aspire 5
 */
public class MenuAppointment extends javax.swing.JFrame {

    /**
     * Creates new form MenuUser
     */
    public MenuAppointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioButtonDiaryPrivacy = new javax.swing.ButtonGroup();
        LabelAppointment = new javax.swing.JLabel();
        LabelGreetingAppoint2 = new javax.swing.JLabel();
        ButtonAppointmentHistory = new javax.swing.JButton();
        ButtonNewAppointment = new javax.swing.JButton();
        ButtonBack = new javax.swing.JButton();
        LogoInnerPeace = new javax.swing.JLabel();
        jBackground = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InnerPeace");
        setName("MenuUser"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(709, 483));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelAppointment.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        LabelAppointment.setForeground(new java.awt.Color(0, 102, 153));
        LabelAppointment.setText("My Appointment");
        getContentPane().add(LabelAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, 70));

        LabelGreetingAppoint2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        LabelGreetingAppoint2.setForeground(new java.awt.Color(255, 255, 255));
        LabelGreetingAppoint2.setText("IRL hooman, because you're lonely lol");
        getContentPane().add(LabelGreetingAppoint2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 530, 30));

        ButtonAppointmentHistory.setBackground(java.awt.Color.pink);
        ButtonAppointmentHistory.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        ButtonAppointmentHistory.setForeground(new java.awt.Color(0, 102, 153));
        ButtonAppointmentHistory.setText("Appointment History");
        ButtonAppointmentHistory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonAppointmentHistory.setBorderPainted(false);
        ButtonAppointmentHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonAppointmentHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonAppointmentHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonAppointmentHistoryMouseExited(evt);
            }
        });
        ButtonAppointmentHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAppointmentHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAppointmentHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 340, 60));

        ButtonNewAppointment.setBackground(java.awt.Color.pink);
        ButtonNewAppointment.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        ButtonNewAppointment.setForeground(new java.awt.Color(0, 102, 153));
        ButtonNewAppointment.setText("New Appointment");
        ButtonNewAppointment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonNewAppointment.setBorderPainted(false);
        ButtonNewAppointment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonNewAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonNewAppointmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonNewAppointmentMouseExited(evt);
            }
        });
        ButtonNewAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNewAppointmentActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNewAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 340, 60));

        ButtonBack.setBackground(java.awt.Color.pink);
        ButtonBack.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        ButtonBack.setForeground(new java.awt.Color(0, 102, 153));
        ButtonBack.setText("Back");
        ButtonBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonBack.setBorderPainted(false);
        ButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonBackMouseExited(evt);
            }
        });
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 110, 30));

        LogoInnerPeace.setIcon(new javax.swing.ImageIcon("D:\\Buat kuliah\\Semester 2\\OOP\\TugasBesar\\TubesInnerPeace\\src\\main\\java\\OOP_InnerPeace\\logo_innerpeace1.png")); // NOI18N
        getContentPane().add(LogoInnerPeace, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 250, 480));

        jBackground.setBackground(new java.awt.Color(77, 150, 255));
        getContentPane().add(jBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void ButtonNewAppointmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonNewAppointmentMouseEntered
        ButtonNewAppointment.setBackground(Color.lightGray);
    }//GEN-LAST:event_ButtonNewAppointmentMouseEntered

    private void ButtonNewAppointmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonNewAppointmentMouseExited
        ButtonNewAppointment.setBackground(Color.pink);
    }//GEN-LAST:event_ButtonNewAppointmentMouseExited

    private void ButtonNewAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNewAppointmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonNewAppointmentActionPerformed

    private void ButtonAppointmentHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAppointmentHistoryMouseEntered
        ButtonAppointmentHistory.setBackground(Color.lightGray);
    }//GEN-LAST:event_ButtonAppointmentHistoryMouseEntered

    private void ButtonAppointmentHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAppointmentHistoryMouseExited
        ButtonAppointmentHistory.setBackground(Color.pink);
    }//GEN-LAST:event_ButtonAppointmentHistoryMouseExited

    private void ButtonAppointmentHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAppointmentHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAppointmentHistoryActionPerformed

    private void ButtonBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBackMouseEntered
        ButtonBack.setBackground(Color.lightGray);
    }//GEN-LAST:event_ButtonBackMouseEntered

    private void ButtonBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBackMouseExited
        ButtonBack.setBackground(Color.pink);
    }//GEN-LAST:event_ButtonBackMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAppointmentHistory;
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonNewAppointment;
    private javax.swing.JLabel LabelAppointment;
    private javax.swing.JLabel LabelGreetingAppoint2;
    private javax.swing.JLabel LogoInnerPeace;
    private javax.swing.ButtonGroup RadioButtonDiaryPrivacy;
    private javax.swing.JPanel jBackground;
    // End of variables declaration//GEN-END:variables
}
